### ISSUE TITLE
Wrong npm package name in readme

### ISSUE THREAD

**Issue by AlexandrDiakov** [matin-mortazavi/color-plugin-editorjs#1]
Hey!
Your readme says to install package with `npm install color-plugin-editorjs`, when in reality it's published under different name: `color-plugin-tool-editorjs`.

Also it seem like it should be imported as default, like `import ColorTool from "color-plugin-editorjs"` while readme says its `import { ColorTool } from "color-plugin-editorjs"`

**Comment by matin-mortazavi** [comment]
HI!
thank you for reporting
get fixed ✅
